[package]
name = "encodedvenom/remotecomponent"
version = "1.0.2"
description = "An extension to sleitnick/component that allows for remote communication."
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TableUtil = "sleitnick/table-util@^1.0"
Comm = "sleitnick/comm@^1.0.1"
